#!/bin/sh

source /etc/profile.d/modules.sh
module load python/GEOSpyD comp/intel/19.1.3.304 mpi/impi/19.1.3.304
eval "$(conda shell.bash hook)"
conda activate hb.env

hb_repo_dir='/gpfsm/dnb31/jgbaker//tess/heartbeats/repos/'
hb_mcmc_py=${hb_repo_dir}'tess-short-binaries/src/mcmc/HB_MCMC2.py'

cd $1

chain=$(echo *_t0.dat)
ds="data_style.json"

if [ $# -eq 2 ]; then
   if [ -f "$2" ]; then
      ds=$2
   else
      echo "Didn't find $2 in:"
      ls 
      period=$2
   fi
fi
		
echo "ds $ds"
echo "period $period"


cmd="python3 ${hb_mcmc_py} --data_style=$ds --hb_style=hb_style.json --plotSamples=[${chain}:25%,:50%,:]"

if [[ ! -z "$period" ]] ; then
    cmd="$cmd --period=$2"
fi

echo $cmd
eval $cmd 
